README.md

This adds Slack and license badges to the README. Bling bling!

Add a couple of badges

---

.editorconfig

Just making sure this file gets fully utilized. 😄 
I included a few languages which are not currently in the repo, but I could easily see them being added in the future.

Add a few more rules to the EditorConfig, including language-specific

---

docs/Internals.md

- this complements the API content for new language authors and people contributing features and bug fixes

add dir structure info to internal documentation

---

docs/Internals.md

- added thread safety note regarding Secure Memory secret read
- added Key Cache implementation notes around TTL and duplicates

added a couple implementation details to Internals

---

.circleci/config.yml

- added java test and sample apps to circleci config. just need to uncomment once CD is in place
- had to uprev circleci maven cache

CI stubbing for remaining java projects

---

.circleci/config.yml
languages/java/app-encryption/pom.xml
languages/java/app-encryption/src/test/java/com/godaddy/asherah/appencryption/persistence/DynamoDbMetastorePersistenceImplTest.java

- use local dynamodb to run tests

Local dynamodb

---

README.md
docs/CodeStructure.md
languages/java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/Partition.java
languages/java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/SessionFactory.java
languages/java/app-encryption/src/test/java/com/godaddy/asherah/appencryption/PartitionTest.java
languages/java/app-encryption/src/test/java/com/godaddy/asherah/appencryption/SessionFactoryTest.java
languages/java/app-encryption/src/test/java/com/godaddy/asherah/appencryption/json/AppJsonEncryptionImplTest.java
tests/java/test-app/src/main/java/com/godaddy/asherah/testapp/utils/SessionFactoryGenerator.java

- Rename systemId to serviceId
- Update corresponding documentation

Rename systemId to serviceId

---

languages/csharp/AppEncryption/README.md

Changes in documentation for C# session caching functionality.
This should be merged after https://github.com/godaddy/asherah/pull/118 and https://github.com/godaddy/asherah/pull/119

C sharp documentation

---

server/README.md
server/samples/clients/node/.eslintrc.json
server/samples/clients/node/.gitignore
server/samples/clients/node/Dockerfile
server/samples/clients/node/README.md
server/samples/clients/node/appencryption_client.js
server/samples/clients/node/package-lock.json
server/samples/clients/node/package.json
server/samples/docker-compose-node.yaml
server/samples/docker-compose-python.yaml

-  Add node gRPC client
- Add docker-compose file for node client
- Rename docker-compose file for python client

Node grpc client

---

go/appencryption/scripts/release_prod.sh
go/securememory/scripts/release_prod.sh

Update artifact name for Go

---

.circleci/config.yml
java/app-encryption/pom.xml

- Update circleci config
- Update version

Release JAVA AE v0.1.0

---

.circleci/config.yml
java/app-encryption/pom.xml
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/persistence/AdhocPersistence.java
java/app-encryption/src/main/java/com/godaddy/asherah/crypto/AeadCrypto.java
java/app-encryption/src/main/java/com/godaddy/asherah/crypto/BasicExpiringCryptoPolicy.java

The earlier release was failing due to missing javadocs. Added them in this PR.

Update missing javadocs

---

go/appencryption/README.md
go/securememory/README.md

- Add installation step
- Update godoc link

Go documentation update

---

.codecov.yml

- Temporarily remove server from codecov
Will need to be added back along with exclusion of auto-generated files

Temporarily remove server from codecov

---

.circleci/config.yml
codecov.yml
csharp/AppEncryption/scripts/integration_test.sh
csharp/AppEncryption/scripts/test.sh
csharp/SecureMemory/scripts/test.sh

- Rename `.codecov.yml` to `codecov.yml`
- Ignore autogenerated and server startup files
- Add `conf: codecov.yml` to codecov upload step in circleci config
- Update codecov.yml as per [suggestion](https://community.codecov.io/t/ignore-option-not-working/1417) from codecov support (

Codecov exclude files

---

server/go/README.md
server/go/go.mod
server/go/go.sum
server/go/pkg/server/options.go
server/go/pkg/server/server.go

- appencryption bumped to 0.1.1
- add flag to expose new region-suffix feature

[server/go] add --enable-region-suffix flag

---

csharp/AppEncryption/AppEncryption/AppEncryption.csproj
csharp/AppEncryption/Crypto/Crypto.csproj
csharp/AppEncryption/Directory.Build.props
csharp/SecureMemory/Directory.Build.props

- update SecureMemory dependency to v0.1.2 (Windows support)
- add Logging dependency (temporary)

[C#] AppEncryption v0.1.2

---

java/app-encryption/README.md
java/app-encryption/pom.xml

Release Java AE v0.1.1

---

java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/SessionFactory.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/persistence/DynamoDbMetastoreImpl.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/persistence/Metastore.java
java/app-encryption/src/test/java/com/godaddy/asherah/appencryption/SessionFactoryTest.java
java/app-encryption/src/test/java/com/godaddy/asherah/appencryption/persistence/DynamoDbMetastoreImplTest.java
java/app-encryption/src/test/java/com/godaddy/asherah/appencryption/persistence/JdbcMetastoreImplTest.java

- Rename withRegionSuffix method to withKeySuffix
- Rename regionSuffix variable to keySuffix

Java: Rename method and variable

---

.circleci/config.yml
samples/go/referenceapp/README.md
samples/go/referenceapp/go.mod
samples/go/referenceapp/go.sum
samples/go/referenceapp/main.go
server/go/README.md
server/go/go.mod
server/go/go.sum
server/go/pkg/server/options.go
server/go/pkg/server/server.go
server/go/pkg/server/server_test.go

server:
- add --dynamodb-table-name flag
reference app: 
- new flags: --dynamodb-endpoint, --dynamodb-region, --dynamodb-table-name
- updated docs

[Go] Use latest AE in the server and ref-app

---

csharp/AppEncryption/README.md
samples/csharp/ReferenceApp/README.md
samples/csharp/ReferenceApp/ReferenceApp/Options.cs
samples/csharp/ReferenceApp/ReferenceApp/ReferenceApp.cs
samples/csharp/ReferenceApp/ReferenceApp/ReferenceApp.csproj

- updated documentation for global tables in the SDK
- updated documentation for configuring the reference app

[C#] : Update reference app and documentation

---

docs/Metastore.md
scripts/revoke_keys_dynamodb.py

- Add an optional flag for table name
- Update link to utility scripts in Metastore.md

Update DynamoDb revoke script

---

go/appencryption/integration_test.go
go/appencryption/pkg/persistence/dynamodb.go
go/appencryption/pkg/persistence/dynamodb_integration_test.go
go/appencryption/pkg/persistence/dynamodb_test.go
go/appencryption/pkg/persistence/persistencetest/dynamodb.go

- split integration tests into separate code file
- dynamodb integration test util code moved to new package: persistence/persistencetest
- new integration test for dynamodb region suffix backwards compatibility

[go] dynamodb integration tests

---

server/java/checkstyle.xml
server/java/pom.xml
server/java/src/main/java/com/godaddy/asherah/grpc/AppEncryptionImpl.java
server/java/src/main/java/com/godaddy/asherah/grpc/DynamoDbConfig.java
server/java/suppressions.xml

- Add JavaDocs for all public methods
- Update maven-checkstyle-plugin version
- Use updated checkstyle

[Java] Server: Add JavaDocs

---

build/java/build.sh
build/java/clean.sh
build/java/release_prod.sh
build/java/test.sh
docs/SystemRequirements.md
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/DefaultPartition.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/Partition.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/Session.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/SessionBytesImpl.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/SessionFactory.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/SessionJsonImpl.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/SuffixedPartition.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/envelope/EnvelopeEncryption.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/envelope/EnvelopeEncryptionBytesImpl.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/envelope/EnvelopeEncryptionJsonImpl.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/envelope/EnvelopeKeyRecord.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/envelope/KeyMeta.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/exceptions/AppEncryptionException.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/exceptions/KmsException.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/exceptions/MetadataMissingException.java

Add JavaDocs for the following packages:
- com.godaddy.asherah.appencryption
- com.godaddy.asherah.appencryption.envelope
- com.godaddy.asherah.appencryption.exceptions

[Java] AE: Add JavaDocs

---

csharp/AppEncryption/AppEncryption/DefaultPartition.cs
csharp/AppEncryption/AppEncryption/Envelope/EnvelopeEncryptionBytesImpl.cs
csharp/AppEncryption/AppEncryption/Envelope/EnvelopeEncryptionJsonImpl.cs
csharp/AppEncryption/AppEncryption/Envelope/EnvelopeKeyRecord.cs
csharp/AppEncryption/AppEncryption/Envelope/IEnvelopeEncryption.cs
csharp/AppEncryption/AppEncryption/Envelope/KeyMeta.cs
csharp/AppEncryption/AppEncryption/Exceptions/KmsException.cs
csharp/AppEncryption/AppEncryption/Exceptions/MetadataMissingException.cs
csharp/AppEncryption/AppEncryption/Partition.cs
csharp/AppEncryption/AppEncryption/Session.cs
csharp/AppEncryption/AppEncryption/SessionBytesImpl.cs
csharp/AppEncryption/AppEncryption/SessionFactory.cs
csharp/AppEncryption/AppEncryption/SessionJsonImpl.cs
csharp/AppEncryption/AppEncryption/SuffixedPartition.cs
csharp/AppEncryption/Crypto/Crypto.csproj
csharp/AppEncryption/Crypto/Exceptions/AppEncryptionException.cs

Namespaces covered:
- GoDaddy.Asherah.AppEncryption
- GoDaddy.Asherah.AppEncryption.Exceptions
- GoDaddy.Asherah.AppEncryption.Envelope
Private and internal methods will be documented in a separate task.

Add docs for public methods in C#

---

.circleci/config.yml
build/java/integration_test.sh
java/app-encryption/pom.xml
java/app-encryption/scripts/integration_test.sh
java/app-encryption/src/it/java/com/godaddy/asherah/ConfigReader.java
java/app-encryption/src/it/java/com/godaddy/asherah/TestConfiguration.java
java/app-encryption/src/it/java/com/godaddy/asherah/TestSetup.java
java/app-encryption/src/it/java/com/godaddy/asherah/multithreaded/MultiFactoryThreadedIT.java
java/app-encryption/src/it/java/com/godaddy/asherah/multithreaded/MultiPartitionMultiThreadedIT.java
java/app-encryption/src/it/java/com/godaddy/asherah/multithreaded/SessionByteMultiThreadedIT.java
java/app-encryption/src/it/java/com/godaddy/asherah/multithreaded/SessionJsonMultiThreadedIT.java
java/app-encryption/src/it/java/com/godaddy/asherah/regression/AppEncryptionParameterizedIT.java
java/app-encryption/src/it/java/com/godaddy/asherah/regression/CacheMock.java
java/app-encryption/src/it/java/com/godaddy/asherah/regression/CryptoKeyHolder.java
java/app-encryption/src/it/java/com/godaddy/asherah/regression/DecryptMetastoreInteractions.java
java/app-encryption/src/it/java/com/godaddy/asherah/regression/DynamoDbGlobalTableIT.java
java/app-encryption/src/it/java/com/godaddy/asherah/regression/EncryptMetastoreInteractions.java
java/app-encryption/src/it/java/com/godaddy/asherah/regression/MetastoreMock.java
java/app-encryption/src/it/java/com/godaddy/asherah/regression/SessionBytesIT.java
java/app-encryption/src/it/java/com/godaddy/asherah/regression/SessionJsonIT.java
java/app-encryption/src/it/java/com/godaddy/asherah/securememory/multithreaded/MultiThreadedSecretIT.java
java/app-encryption/src/it/java/com/godaddy/asherah/testhelpers/Constants.java
java/app-encryption/src/it/java/com/godaddy/asherah/testhelpers/KeyState.java
java/app-encryption/src/it/java/com/godaddy/asherah/utils/DateTimeUtils.java
java/app-encryption/src/it/java/com/godaddy/asherah/utils/PayloadGenerator.java
java/app-encryption/src/it/java/com/godaddy/asherah/utils/PersistenceFactory.java
java/app-encryption/src/it/java/com/godaddy/asherah/utils/SessionFactoryGenerator.java
java/app-encryption/src/it/resources/config.yaml

Moved integration tests from `test-app` to the library itself.
Additional task to remove the `test-app` job and its contents will be done at a later stage.
Additional integration tests to verify cross partition encryption/decryption would be written once this gets merged in.

Integration tests migration

---

csharp/Logging/Directory.Build.props
csharp/Logging/Logging.Tests/Logging.Tests.csproj
csharp/Logging/Logging/Logging.csproj

Step 1 of 3 towards resolving https://github.com/godaddy/asherah/issues/259

[C#] Logging: Convert StyleCop to a development dependency

---

java/app-encryption/pom.xml

- This version solves #252 for Java
- Adds a regression test to verify that cross-partition decrypt operations fail

[Java]Release AppEncryption v0.1.3

---

java/app-encryption/pom.xml
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/SessionFactory.java
java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/envelope/EnvelopeEncryptionJsonImpl.java

* Fix JavaDoc issues
* Add javadoc check as part of build script
* Execute maven-javadoc-plugin during compile for JavaDoc validation
* Remove maven-javadoc-plugin from release profile

[Java] AppEncryptionv0.1.3

---

csharp/AppEncryption/README.md
samples/csharp/ReferenceApp/README.md
samples/csharp/ReferenceApp/ReferenceApp/Options.cs
samples/csharp/ReferenceApp/ReferenceApp/ReferenceApp.cs
samples/csharp/ReferenceApp/ReferenceApp/ReferenceApp.csproj

- Update reference app
- Update documentation

[C#]Use latest version of AE

---

.circleci/config.yml
.circleci/wss-unified-agent.config

Add a new workflow that runs WSS scans at 11:00 every Monday.
The scan will run only on the master branch on the godaddy/asherah repo (not on forks)

Integrate WhiteSource scans as a scheduled workflow

---

.pre-commit-config.yaml

This adds the Tartufo scan to our pre-commit hooks

Add tartufo check

---

csharp/SecureMemory/Directory.Build.props

[C#] bump SecureMemory to v0.1.4

---

.circleci/config.yml
samples/java/reference-app/README.md
samples/java/reference-app/checkstyle.xml
samples/java/reference-app/pom.xml
samples/java/reference-app/src/main/java/com/godaddy/asherah/referenceapp/App.java

also includes additional dependency upgrades, including JDK-11 build support

[Java] Update reference-app to use latest AE (v0.1.4)

---

.circleci/wss-unified-agent.config

Update Package Manager Dependency Resolvers in the config file based
on details provided in the respective documents:
Java/Maven - https://whitesource.atlassian.net/wiki/spaces/WD/pages/536182791/Maven+Integration
C# - https://whitesource.atlassian.net/wiki/spaces/WD/pages/536182785/NuGet+Integration
Go - https://whitesource.atlassian.net/wiki/spaces/WD/pages/494960641/Go+Integration

Update WhiteSource config

---

.github/workflows/draft-release.yml

This workflow automates the creation of a release draft when
a new version tag is pushed.

New actions workflow: Draft release

---

csharp/AppEncryption/Crypto/AeadCrypto.cs
csharp/AppEncryption/Crypto/BasicExpiringCryptoPolicy.cs
csharp/AppEncryption/Crypto/CryptoPolicy.cs
csharp/AppEncryption/Crypto/Keys/CryptoKey.cs
csharp/AppEncryption/Crypto/Keys/SecretCryptoKey.cs
csharp/AppEncryption/Crypto/Keys/SecureCryptoKeyDictionary.cs
csharp/AppEncryption/Crypto/Keys/SharedCryptoKey.cs
csharp/AppEncryption/Crypto/NeverExpiredCryptoPolicy.cs
csharp/AppEncryption/Crypto/NonceGenerator.cs
csharp/AppEncryption/Directory.Build.props

- Add documentation for Crypto public methods
- Bump C# version

Add documentation for Crypto public methods. Phase 2.

---

csharp/AppEncryption/AppEncryption.IntegrationTests/AppEncryption.IntegrationTests.csproj
csharp/AppEncryption/AppEncryption.IntegrationTests/SecureMemory/Multithreaded/MultiThreadedSecretTest.cs
csharp/AppEncryption/AppEncryption.Tests/AppEncryption.Tests.csproj
csharp/AppEncryption/AppEncryption/AppEncryption.csproj
csharp/AppEncryption/Crypto/Crypto.csproj
csharp/AppEncryption/Directory.Build.props
csharp/AppEncryption/README.md
csharp/SecureMemory/README.md

- Updated dependencies in the .NET Asherah projects to reduce likelihood of downstream dependency conflicts

Updated the dependencies in the csharp libraries

---

csharp/AppEncryption/AppEncryption/AppEncryption.csproj
csharp/AppEncryption/Directory.Build.props
csharp/AppEncryption/README.md

Added System.Text.Encodings.Web as top-level dependency

---

.circleci/config.yml

Disable codcov following https://about.codecov.io/security-update/

Disable codecov

---

java/app-encryption/pom.xml

- Release new version of Java App Encryption with fix for cross-region decryption bug

Java App Encryption Release

---

.github/workflows/ci.yml

- Trigger CI workflow on master and release branches

Update workflow triggers

---

.github/workflows/ci.yml

Based on @tarkatronic's suggestion, updating the cache keys to see if that results in correct cache restores.

Update cache key

---

csharp/AppEncryption/AppEncryption.IntegrationTests/AppEncryption.IntegrationTests.csproj
csharp/AppEncryption/AppEncryption.Tests/AppEncryption.Tests.csproj
csharp/AppEncryption/AppEncryption/AppEncryption.csproj
csharp/SecureMemory/SecureMemory.Tests/SecureMemory.Tests.csproj

Updates projects in csharp/AppEncryption and csharp/SecureMemory to the latest version of libraries.

Update csharp libraries

---

csharp/AppEncryption/AppEncryption.IntegrationTests/AppEncryption.IntegrationTests.csproj
csharp/AppEncryption/AppEncryption.Tests/AppEncryption.Tests.csproj
csharp/AppEncryption/AppEncryption/AppEncryption.csproj
csharp/AppEncryption/Crypto/Crypto.csproj
csharp/Logging/Logging.Tests/Logging.Tests.csproj
csharp/Logging/Logging/Logging.csproj
csharp/SecureMemory/SecureMemory.Tests/SecureMemory.Tests.csproj
csharp/SecureMemory/SecureMemory/SecureMemory.csproj

Updates all projects to the latest versions of libraries.

Update nuget dependencies

---

csharp/AppEncryption/Crypto/Crypto.csproj
csharp/AppEncryption/Directory.Build.props

- Use latest Logging and SecureMemory
- Update C# Asherah to 0.2.7 for release.

Use latest Logging and SecureMemory

---

server/samples/clients/node/Dockerfile

Update node version

---

server/java/Dockerfile
server/java/README.md
server/java/pom.xml
server/java/src/main/java/com/godaddy/asherah/grpc/AppEncryptionConfig.java
server/java/src/main/java/com/godaddy/asherah/grpc/DynamoDbConfig.java
server/java/src/main/java/com/godaddy/asherah/grpc/ServerApp.java
server/java/src/test/java/com/godaddy/asherah/grpc/AppEncryptionConfigTest.java

- Update server to use latest AE (v0.2.3)
- Dockerfile
- use multi-stage build (jar no longer has to to be built in advance)
- java 17
- use default values for required env var
- Updated readme

Java Server Updates

---

csharp/SecureMemory/Directory.Build.props

C# SM Version Bump

---

.github/workflows/ci.yml
csharp/AppEncryption/AppEncryption.IntegrationTests/AppEncryption.IntegrationTests.csproj
csharp/AppEncryption/AppEncryption.Tests/AppEncryption.Tests.csproj
csharp/AppEncryption/AppEncryption/AppEncryption.csproj
csharp/AppEncryption/Crypto/Crypto.csproj
csharp/AppEncryption/scripts/install-dotnet-3.1.sh
csharp/Logging/scripts/install-dotnet-3.1.sh
samples/csharp/ReferenceApp/scripts/install-dotnet-3.1.sh

Update to latest SecureMemory and switch all builds to sdk:6.0 with 3.1 targeting pack

Update to latest SecureMemory

---

java/app-encryption/pom.xml

- added missing dependencies
- org.apache.commons:commons-lang3
- com.fasterxml.jackson.core:jackson-databind
- org.checkerframework:checker-qual
- com.amazonaws:aws-java-sdk-core
- org.junit.jupiter:junit-jupiter-api
- org.mockito:mockito-core
- moved com.fasterxml.jackson.dataformat:jackson-dataformat-cbor to dependency management

dependency updates and fixes

---

server/java/pom.xml
server/java/target/generated-sources/protobuf/grpc-java/com/godaddy/asherah/grpc/AppEncryptionGrpc.java
server/java/target/generated-sources/protobuf/java/com/godaddy/asherah/grpc/AppEncryptionProtos.java

grpc -> 1.51.0
protobuf -> 3.21.7
netty -> 4.1.85.Final
junit -> 5.9.1
+ added explicit declarations for missing dependencies

java server dependency updates

---

.github/workflows/ci.yml
.github/workflows/draft-release.yml
.github/workflows/run-wss-scans.yml
.github/workflows/sync-release.yml
.tartufo-excludes
tartufo.toml

- Update GHA SHAs to latest released version
- Update tartufo config

Update GHA SHAs to latest released versions

---

.github/workflows/ci.yml
java/secure-memory/pom.xml

- Update java version
- Update CI to run on hosted runners instead of containers
- Reorganize POM

Update Java SM dependencies and java version

---

server/java/pom.xml
server/java/target/generated-sources/protobuf/grpc-java/com/godaddy/asherah/grpc/AppEncryptionGrpc.java
server/java/target/generated-sources/protobuf/java/com/godaddy/asherah/grpc/AppEncryptionProtos.java

Updated Java server dependencies and regenerated protos.
- grpc -> 1.54.1
- protobuf -> 3.22.3
- netty -> 4.1.92.Final
- appencryption -> 0.2.5

Updated Java Server Dependencies

---

samples/java/reference-app/pom.xml
server/java/pom.xml
server/java/src/test/java/com/godaddy/asherah/grpc/AppEncryptionConfigTest.java
tests/cross-language/java/pom.xml

Update Java AE version in sample, server and cross language tests.

Update Java AE version in the sample app, server and CLTF

---

go/appencryption/pkg/crypto/aead/aead.go
go/appencryption/pkg/crypto/aead/aes256gcm.go
go/appencryption/pkg/crypto/aead/aes256gcm_test.go

- Input validation updated to include explicit guards around the computed size of the slice used for plaintext storage. These guards prevent integer overflow and esure the size of the input data is supported by the cipher.

Improved input validation on encrypt

---

server/java/src/test/java/com/godaddy/asherah/grpc/AppEncryptionServerTest.java

- Improved test resiliency
- construct server spy in main thread

Unit test updates

---

.github/workflows/ci.yml

- Update `server-samples` job to run on `ubuntu-latest`

CI Updates/Fixes

---

java/secure-memory/pom.xml

- multiple dependency updates
- bump version to v0.1.3

[java securememory] update dependencies, bump version

---

java/app-encryption/pom.xml

- upgrade secure memory dependency to latest
- bump version to v0.3.1

[java appencryption] update dependencies, bump version

---

java/app-encryption/pom.xml

- [java appencryption] upgrade Bouncy Castle to latest (1.77)

[java appencryption] upgrade bouncycastle to latest (1.77)

---

.github/workflows/ci.yml
server/samples/clients/node/package-lock.json
server/samples/clients/python/requirements.txt
server/samples/clients/test_clients.sh
tests/cross-language/scripts/decrypt_all.sh
tests/cross-language/scripts/encrypt_all.sh
tests/cross-language/sidecar/requirements.txt

- updated runtimes:
- node -> 20.x
- go -> 1.22
- python -> 3.12
- test_client.sh: now sleeps for up to 30s after starting server
- node sample client: regenerated package-lock.json for version 3
- upgrade grpcio[-tools] to latest 1.65.1 (python server sample and xlang client)

Runtime & dependency updates for cross-languange and server samples jobs

---

.github/workflows/go-appencryption-ci.yml
.github/workflows/go-pr.yml

- bump golangci-lint version to v1.60.1
- bump golangci-lint-action to v6.1.0
- disable cache
- minor job order fix in `[Go] AppEncryption CI` - run unit tests after build (not in parallel)
- use golangci-lint-action for linting steps in `[Go] Pull Request`

[Go] Update golangci-lint action and tool version

---

.github/workflows/cross-language-validation.yml

- update to cross-language tests to use golangci-lint-action for Go linting step

[Go] minor update to cross-language tests to use golangci-lint-action for Go linting step

---

.github/workflows/ci.yml

- disabled go linting tasks in ci.yml (old workflows)

[ci.yml] disable go linting

---

.github/workflows/ci.yml

- renamed setup steps: "Set up Go 1.19" -> "Set up Go (stable)"

[ci.yml] minor updates

---

.github/dependabot.yml

This PR adds a Dependabot configuration file, `dependabot.yml`, to the repository. This initial configuration defines update behavior for the core SDK projects. Note that automated PR creation only enabled for `github-actions` and `gomod` package managers.

initial dependabot config file

---

tests/cross-language/scripts/decrypt_all.sh
tests/cross-language/scripts/encrypt_all.sh

- encapsulate wait logic into a function called wait_for_socket, add timeout of 60 seconds

[CLTF] Refactor "wait for socket" functionality, add timeout

---

csharp/AppEncryption/AppEncryption.Tests/AppEncryption/Persistence/DynamoDbMetastoreImplTest.cs
csharp/AppEncryption/AppEncryption.Tests/AppEncryption/SessionFactoryTest.cs

- use `async Task` instead of `void` for async tests
- use `Assert.Fail(msg)` instead of `Assert.True(false, msg)`

lint cleanup

---

.pre-commit-config.yaml
tartufo.toml

* [na] Tests (if applicable)
* [na] Documentation (if applicable)
Resolves #1108 
- Updates pre-commit and tartufo to latest versions
- Updates tartufo.toml rules to match latest version signature syntax

update tartufo and precommit

---

.github/workflows/go-securememory-ci.yml
.github/workflows/java-securememory-ci.yml
.pre-commit-config.yaml
csharp/AppEncryption/AppEncryption/AppEncryption.csproj
csharp/SecureMemory/SecureMemory/SecureMemory.csproj
java/app-encryption/README.md
samples/csharp/ReferenceApp/README.md

- exclude generated source from pre-commit hooks
- global cleanup via `pre-commit run --all`

exclude generated source from pre-commit hooks, global cleanup via `pre-commit run --all`

---

.github/workflows/csharp-appencryption-ci.yml
.github/workflows/csharp-appencryption-integration.yml
.github/workflows/csharp-logging-ci.yml
.github/workflows/csharp-pr.yml
.github/workflows/csharp-securememory-ci.yml

- Upgrade `actions/cache` to [v4.2.0](https://github.com/actions/cache/releases/tag/v4.2.0) (pinned SHA: 1bd1e32a3bdc45362d1e726936510720a7c30a57)

upgrade actions/cache to v4.2.0

---

tests/cross-language/java/pom.xml

Update cross-language test project dependencies, replacing the `junit-jupiter-engine` dependency with `junit-jupiter-api`
Resolves #1196

[java cltf] junit-jupiter dependency fix

---

java/secure-memory/pom.xml

[java securememory] bump version

---

.github/workflows/ci.yml

- use ubuntu-22.04 for legacy cross-language tests (ci.yml)

use net6 for legacy cross-language tests

---

java/app-encryption/pom.xml

- upgrade securememory to 0.1.5
- bump package version to 0.3.2

[java appencryption] upgrade securememory to 0.1.5, bump version

---

csharp/Logging/Directory.Build.props

[csharp logging] bump version

---

csharp/SecureMemory/Directory.Build.props

[csharp securememory] bump version

---

server/samples/clients/python/requirements.txt
tests/cross-language/sidecar/requirements.txt

- update grpcio and grpcio-tools to 1.66.2 (python server sample and cross-language tests)

Update grpcio to 1.66.2 (python 3.13 support)

---

.github/workflows/cross-language-validation.yml
.github/workflows/go-appencryption-ci.yml
.github/workflows/go-pr.yml
.github/workflows/go-securememory-ci.yml
go/appencryption/.golangci.yml
go/appencryption/parameterized_test.go
samples/go/referenceapp/main.go

- update golangci-lint to latest: binary -> v1.64.2, action -> v6.3.2

update golangci-lint to latest

---

.github/workflows/csharp-appencryption-release.yml
.github/workflows/csharp-logging-release.yml
.github/workflows/csharp-securememory-release.yml
.github/workflows/go-appencryption-release.yml
.github/workflows/go-securememory-release.yml
.github/workflows/java-appencryption-release.yml
.github/workflows/java-securememory-release.yml

This PR attempts to resolve the ["Unknown Event" error](https://github.com/godaddy/asherah/actions/runs/13659403836) seen when GH attempts to parse the `workflow_run` triggers of the new release workflows.
-  escape special chars (ie brackets) in workflow triggers

[cicd] updated triggers for release workflows

---

.github/workflows/csharp-logging-release.yml

- csharp-logging-release.yml: download artifact via `gh` CLI

[cicd] download artifact via `gh` CLI

---

.github/workflows/csharp-logging-release.yml

- csharp-logging-release.yml: checkout trigger branch, set working directory

[cicd] c# release workflow updates

---

.github/workflows/csharp-appencryption-ci.yml
.github/workflows/csharp-appencryption-release.yml
.github/workflows/csharp-logging-ci.yml
.github/workflows/csharp-logging-release.yml
.github/workflows/csharp-securememory-ci.yml
.github/workflows/csharp-securememory-release.yml
.github/workflows/go-appencryption-ci.yml
.github/workflows/go-appencryption-release.yml
.github/workflows/go-securememory-ci.yml
.github/workflows/go-securememory-release.yml
.github/workflows/java-appencryption-ci.yml
.github/workflows/java-appencryption-release.yml
.github/workflows/java-securememory-ci.yml
.github/workflows/java-securememory-release.yml

- replaced `workflow_run` with `workflow_call` triggers
- updated each ci workflow to call its corresponding release workflow
- other fixes

[cicd] updated triggers for new release workflows

---

.github/workflows/csharp-appencryption-ci.yml
.github/workflows/csharp-appencryption-release.yml
.github/workflows/csharp-logging-ci.yml
.github/workflows/csharp-logging-release.yml
.github/workflows/csharp-securememory-ci.yml
.github/workflows/csharp-securememory-release.yml
.github/workflows/go-appencryption-release.yml
.github/workflows/go-securememory-release.yml
.github/workflows/java-appencryption-ci.yml
.github/workflows/java-appencryption-release.yml
.github/workflows/java-securememory-ci.yml
.github/workflows/java-securememory-release.yml

- implicitly pass secrets to reusable release workflows via `secrets: inherit`
- fix working directory paths for java release workflows
- fix typo `s/Envionment/Environment/`
- removed unused inputs (go release workflows)

[cicd] workflow updates

---

.github/workflows/csharp-appencryption-ci.yml
.github/workflows/csharp-logging-ci.yml
.github/workflows/csharp-securememory-ci.yml
.github/workflows/go-appencryption-ci.yml
.github/workflows/go-securememory-ci.yml
.github/workflows/java-appencryption-ci.yml
.github/workflows/java-securememory-ci.yml

The pull_request trigger is needed to ensure CI workflows are triggered for PRs from forks.
- adds the `pull_request` trigger to all CI workflows.

[cicd] add pull_request triggers to all ci workflows

---

csharp/Logging/Directory.Build.props

- Bump version of GoDaddy.Asherah.Logging to 0.2.0

[csharp logging] bump version to 0.2.0

---

csharp/AppEncryption/Crypto/Crypto.csproj
csharp/AppEncryption/Directory.Build.props
csharp/SecureMemory/README.md

- GoDaddy.Asherah.Logging upgraded to latest (v0.2.0)
- GoDaddy.Asherah.SecureMemory upgraded to latest (v0.3.0)
- Bump package version to 0.4.0

[csharp appencryption] Upgrade SecureMemory and Logging, bump version

---

docs/FAQ.md

- Add new Integration and Implementation section with detailed guidance on choosing ProductID and ServiceName for SessionFactory initialization. Include code examples for Java, Go, and C# implementations, best practices, and key construction impact. Reorganize existing content under Architecture and Design Decisions section for better organization.
- Removed byte order marks.

Update FAQ with integration guidance for ProductID and ServiceName

---

csharp/AppEncryption/Directory.Build.props

[csharp appencryption] bump version to 0.8.0
