- languages/csharp/SecureMemory/README.md
- languages/java/secure-memory/README.md
- remove docker build info until we add it back with external cicd effort
- clarified current state of implementation info
- leaving bulk of the info in them as is for now as upcoming golang SM implementation may change how we convey SM info
> minor cleanup in SM READMEs

- .circleci/config.yml
- .codecov.yml
- README.md
- languages/java/secure-memory/README.md
- project-dirs
Fixes #79 and #81 
- includes initial structure/templates for CircleCI and Codecov integration
- there is a leftover/incomplete job that can allow us to only build affected parts of the monorepo -- will come back to that later. there are some misc notes around that in the configs
- note this only handles CI currently. CD will be done separately
- added CircleCI and Codecov badges (codecov will be more accurate once all projects have CI hooks)
- some misc whitespace changes in secure memory readme that can be ignored (they were done to trigger builds in earlier versions of the circleci implementation)
> checkpoint of CircleCI and Codecov infra

- languages/csharp/AppEncryption/AppEncryption.Tests/AppEncryption/Persistence/AdoMetastorePersistenceImplTest.cs
- languages/csharp/AppEncryption/AppEncryption/Persistence/AdoMetastorePersistenceImpl.cs
The way INSERT query was written using (WHERE NOT EXISTS) caused deadlocks when multiple threads try to write the same value at the same time. 
Fixed by always returning a false if the query fails
> Deadlock bug fix

- .circleci/config.yml
Csharp builds were failing in the master branch because restoring an earlier cache, blows out the environment setup.
Changed the order of steps, such that the build environment is setup after restoring cache.
> Fix csharp build errors

- languages/java/app-encryption/pom.xml
- languages/java/app-encryption/src/test/java/com/godaddy/asherah/appencryption/persistence/DynamoDbMetastorePersistenceImplTest.java
- keeps project root clean and avoids having to update gitignore
> move native libs needed for tests to build dir

- .circleci/config.yml
NuGet does not check for all the sub-directories and would fail if we try to do a `dotnet restore` command.
> Create packages directory in setup csharp environment

- samples/csharp/ReferenceApp/ReferenceApp/ReferenceApp.cs
- samples/java/reference-app/src/main/java/com/godaddy/asherah/referenceapp/App.java
Use 32 bytes static master key to keep it consistent with future implementations of `Go`
> Static kms key

- languages/csharp/AppEncryption/AppEncryption.IntegrationTests/Regression/AppEncryptionParameterizedTest.cs
- languages/csharp/AppEncryption/AppEncryption.IntegrationTests/Regression/EncryptMetastoreInteractions.cs
- tests/java/test-app/src/main/java/com/godaddy/asherah/testapp/regression/AppEncryptionParameterizedTest.java
- tests/java/test-app/src/main/java/com/godaddy/asherah/testapp/regression/EncryptMetastoreInteractions.java
- Verify that some method calls actually never happen
- Fixed the case of loading latest SK in encrypt metastore interactions
> Fixed the flow in parameterised tests

- server/go/main.go
The sidecar app is incorrectly checking for `PreferredRegion` twice instead of also checking for `RegionMap` when validating options.
> fixed option check for region map

- samples/go/referenceapp/go.mod
- samples/go/referenceapp/go.sum
- samples/go/referenceapp/main.go
- upgraded appencryption to v0.1.1
- New flags:
- `--enable-region-suffix` flag wraps the new AE `WithDynamoDBRegionSuffix` option
- `--parition-id` flag allows override of default value
> [go/referenceapp] new flags, bump AE to v0.1.1

- csharp/Logging/Directory.Build.props
- Add appropriate repo and license info to the C#  logging release
- Update version as per [note](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/publish-nuget-package)
> Fix C# Logging Release

- csharp/AppEncryption/AppEncryption/AppEncryption.csproj
- csharp/AppEncryption/Crypto/Crypto.csproj
- csharp/AppEncryption/Directory.Build.props
- update SecureMemory dependency to v0.1.2
- add Logging dependency (temporary)
> [C#] bump AppEncryption to v0.1.2

- java/app-encryption/pom.xml
- Update Guava to use the latest version
- Bump AE to v0.1.2 for release
> [Java] Update Guava version to address GitHub security alert

- csharp/AppEncryption/AppEncryption.Tests/AppEncryption/Kms/AwsKeyManagementServiceImplTest.cs
- Newtonsoft.Json has an [issue](https://github.com/JamesNK/Newtonsoft.Json/issues/1437) where DeepEquals fails when order of array elements is different. Adding a custom checker to verify if the test should really fail or if it's just failing due to the aforementioned issue.
> [C#] Update AwsKeyManagementServiceImplTest

- build/java/build.sh
- java/app-encryption/pom.xml
- java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/SessionFactory.java
- java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/envelope/EnvelopeEncryptionJsonImpl.java
- Moved the `maven-javadoc-plugin` out of the release profile block. This will ensure that JavaDocs are generated and validated for every build.
> Fix JavaDoc issues for AE v0.1.3 release

- csharp/SecureMemory/SecureMemory.Tests/SecureMemory.Tests.csproj
This _should_ fix unit test code coverage.
> revert back to using coverlet.msbuild

- .circleci/config.yml
- java/secure-memory/checkstyle.xml
- java/secure-memory/pom.xml
Note: compilation target continues to be JDK-8
> secure-memory: JDK 11 support (build env only), upgraded dependencies

- .circleci/config.yml
- java/app-encryption/checkstyle.xml
- java/app-encryption/pom.xml
Compilation target continues to be JDK-8
- Upgraded dependencies, including secure-memory to v0.1.1
> [Java] app-encryption JDK 11 support (build env only)

- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/ProtectedMemorySecretFactoryTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/ProtectedMemorySecretTest.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/ProtectedMemorySecret.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/ProtectedMemorySecretFactory.cs
Since failure to Dispose of a ProtectedMemorySecret is now a fatal error, it becomes important to be able to figure out which secret usage isn't being disposed of.  Since the fatal error happens in the finalizer thread, there's no good way to identify that.  With this additional bit of configuration for debugging secrets enabled, ProtectedMemorySecret will save the stack trace of the constructor call and include that in the exception message if it hits the finalizer.
> Add creation stack trace debug mode for ProtectedMemorySecret

- .circleci/config.yml
The new "upload-coverage" command makes use of the same bash script
as the codecov orb but wraps the execution in a retry loop.
> Replace codecov orb with a custom command

- .circleci/config.yml
- Execute codecov bash in subshell
- use let builtin for incrementing the counter, also avoid `(( var++ ))` exit code 1 on initial increment
> upload-coverage bugfixss

- .gitignore
- build/csharp/release_prod.sh
- csharp/AppEncryption/AppEncryption/AppEncryption.csproj
- csharp/SecureMemory/Directory.Build.props
- csharp/SecureMemory/PlatformNative/PlatformNative.csproj
- csharp/SecureMemory/SecureMemory.Tests/EndToEndTests.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/Libc/LibcProtectedMemoryAllocatorTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/Libc/ResourceLimitTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/Linux/LinuxOpenSSL11ProtectedMemoryAllocatorTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/Linux/LinuxProtectedMemoryAllocatorTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/Linux/OpenSSLCryptProtectMemoryTests.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/ProtectedMemoryAllocatorTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/ProtectedMemorySecretFactoryTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/ProtectedMemorySecretTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/Windows/WindowsProtectedMemoryAllocatorTest.cs
- csharp/SecureMemory/SecureMemory.Tests/SecretTest.cs
- csharp/SecureMemory/SecureMemory.Tests/SecureMemory.Tests.csproj
- csharp/SecureMemory/SecureMemory.Tests/TransientSecretFactoryTest.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/Linux/LinuxOpenSSL11ProtectedMemoryAllocatorLP64.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/ProtectedMemorySecret.cs
- csharp/SecureMemory/SecureMemory/SecureMemory.csproj
This PR makes the requirement to Dispose of any ProtectedMemorySecret configurable since there are presently cases where not all AppEncryption tests can dispose of all secrets due to limitations in xunit.
> Configure secret disposal requirement

- .circleci/config.yml
- .github/workflows/sync-release.yml
This workflow automates the push from master -> release-x
Also, includes minor update to the existing upload-coverage build step to ensure curl errors are displayed.
> New actions workflow: Sync release branch

- csharp/SecureMemory/Directory.Build.props
- csharp/SecureMemory/PlatformNative/LP64/Linux/OpenSSLCrypto.cs
- csharp/SecureMemory/PlatformNative/LP64/MacOS/MacOSLibcLP64.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/Libc/LibcProtectedMemoryAllocatorTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/ProtectedMemorySecretFactoryTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/ProtectedMemorySecretTest.cs
- csharp/SecureMemory/SecureMemory.Tests/SecretTest.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/Libc/LibcProtectedMemoryAllocatorLP64.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/Linux/LinuxOpenSSL11ProtectedMemoryAllocatorLP64.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/ProtectedMemorySecret.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/ProtectedMemorySecretFactory.cs
- csharp/SecureMemory/SecureMemory/Secret.cs
The locking on ProtectedMemorySecret wasn't done correctly, and it wasn't being caught well by the tests back when we weren't universally calling Dispose.  When we started calling Dispose more often, we would get phantom errors during or after Dispose calls when Interlocked.Exchange would yank the pointer away after the IntPtr.Zero / null check outside of any synchronized context.
In this new version, we use a ReaderWriterLockSlim.EnterReadLock for all read access to the secret, and we use ReaderWriterLockSlim.EnterWriteLock for Dispose.  This allows multiple concurrent readers of the same secret unlike the previous version, and ensures a synchronized context when disposing.
Also in this PR, we ensure that the managed byte[] and managed char[] used in WithSecretBytes and …
> Fix the locking on ProtectedMemorySecret

- .circleci/wss-unified-agent.config
Set `nuget.resolveDependencies` to true so that all dependencies are resolved before running the scan. This should take care of the libraries not getting updated correctly for the C# projects.
> Update nuget dependency resolver

- csharp/AppEncryption/AppEncryption.Tests/AppEncryption/Util/JsonTest.cs
- csharp/AppEncryption/AppEncryption/Util/Json.cs
- csharp/AppEncryption/Directory.Build.props
- docs/SystemRequirements.md
- When retrieving data from a JSON blob, Newtonsoft.Json attempts to parse any data that looks like dates internally as a DateTime. As a result of this, when a date time value is pulled as a string, it uses its own default formatting to make the value different from how it originally was.
To avoid this, we are explicitly setting DateParseHandling to None.
- Bump version for release
> Set DateParseHandling to None

- csharp/SecureMemory/Directory.Build.props
- csharp/SecureMemory/SecureMemory.Tests/SecureMemory.Tests.csproj
- csharp/SecureMemory/SecureMemory/SecureMemory.csproj
- Updated "Microsoft.Extensions.Configuration.Abstractions" to version "5.0.0" in SecureMemory
- Updated test dependencies
- Bumped SecureMemory version to 0.1.10
> Updated packages in .NET SecureMemory projects

- csharp/SecureMemory/Directory.Build.props
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/Libc/LibcProtectedMemoryAllocatorTest.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/Libc/LibcProtectedMemoryAllocatorLP64.cs
The previous implementation suffered from two issues:
- an rlimit of unlimited was managed internally as a resource limit of 0,
leading to a MemoryLimitException on subsequent Alloc() calls.
- an rlimit > long.MaxValue resulted in an overflow condition and a resource
limit of less than 0, also leading to a MemoryLimitExeption.
Resolves #358
> [C#] Fix handling of very large/unlimited memlock rlimit

- .circleci/config.yml
- tests/cross-language/scripts/decrypt_all.sh
- tests/cross-language/scripts/encrypt_all.sh
This PR pins the JRE version installed in the cross-language-tests job to 11.0.7+10-3ubuntu1 since that allows database connections using TLSv1, which isn't allowed in newer versions - https://bugs.openjdk.java.net/browse/JDK-8254713 
Other updates include:
- Use ubuntu:latest image since the required JRE wasn't available in ubuntu:18.04
```
root@66ad93682d8e:/# apt-cache madison openjdk-11-jre
openjdk-11-jre | 11.0.11+9-0ubuntu2~18.04 | http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
openjdk-11-jre | 11.0.11+9-0ubuntu2~18.04 | http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
openjdk-11-jre | 10.0.1+10-3ubuntu1 | http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```
- Update CLTF to use python3.8
> Install openjdk-11 version 11.0.7+10-3ubuntu1

- csharp/AppEncryption/AppEncryption.IntegrationTests/Regression/DynamoDbGlobalTableTest.cs
- csharp/AppEncryption/AppEncryption.Tests/AppEncryption/Persistence/DynamoDBContainerFixture.cs
- csharp/AppEncryption/AppEncryption.Tests/AppEncryption/SuffixedPartitionTest.cs
- csharp/AppEncryption/AppEncryption/SuffixedPartition.cs
- csharp/AppEncryption/Directory.Build.props
- java/app-encryption/pom.xml
- java/app-encryption/src/it/java/com/godaddy/asherah/regression/DynamoDbGlobalTableIT.java
- java/app-encryption/src/main/java/com/godaddy/asherah/appencryption/SuffixedPartition.java
- java/app-encryption/src/test/java/com/godaddy/asherah/appencryption/SuffixedPartitionTest.java
- Update logic to check the start of keyId instead of the entire id for partitioned keys
- Add regression tests for cross-region encryption/decryption
> Fix cross-region decryption bug in Java and C#

- .github/workflows/sync-release.yml
Push action doesn't trigger subsequent workflow ire we're using the default token provided by GitHub Actions. https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854
Use a custom token in the sync-release workflow to trigger subsequent actions.
> Use custom PAT in sync-release

- .github/workflows/ci.yml
- java/app-encryption/pom.xml
- java/secure-memory/pom.xml
- C# jobs need xmllint to extract version from the `Directory.Build.props` file
- Maven GPG plugin coffin must be updated as per https://github.com/actions/setup-java/issues/83 in order for successful maven setup
> Updates for C# and Java release jobs

- build/csharp/release_prod.sh
C# releases currently fail because it is unable to find the required dependencies to build the projects. This is likely caused by an issue with caching. There are quite a few issues (open and closed) in the actions/cache repo. Until a more robust solution is implemented for C# release, build and pack artifacts on the release branches.
https://github.com/godaddy/asherah/issues/380 filed to keep this on our radar.
> Temporarily build and pack C# artifacts

- csharp/AppEncryption/AppEncryption/AppEncryption.csproj
- csharp/AppEncryption/Crypto/Crypto.csproj
Currently, the CI for C# AppEncryption fails with the following error.
```
/home/runner/work/asherah/asherah/csharp/AppEncryption/AppEncryption/AppEncryption/obj/Release/netstandard2.1/.NETStandard,Version=v2.1.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute
```
The proposed solution is derived from this SO article - https://stackoverflow.com/questions/61997928/errorcs0579duplicate-globalsystem-runtime-versioning-targetframeworkattribu
Verified that the solution works here - https://github.com/sushantmimani/asherah/runs/3000940891?check_suite_focus=true
The failure is due to missing secrets in the fork.
> Update C# AE csproj file

- csharp/AppEncryption/AppEncryption/AppEncryption.csproj
- csharp/AppEncryption/Directory.Build.props
Updated dependencies of `GoDaddy.Asherah.AppEncryption`:
- updated AWS dependencies to latest
- removed unused and vulnerable regex package (CVE-2019-0820)
- removed other unused dependencies
> Updated c# AppEncryption dependencies

- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/Libc/LibcProtectedMemoryAllocatorTest.cs
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/ProtectedMemorySecretFactoryTest.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/ProtectedMemorySecretFactory.cs
In addition to the test fixes for multiple platforms (mainly macOS), `ProtectedMemorySecretFactory` will now throw a `PlatformNotSupportedException` when configured with `secureHeapEngine=openssl11` on macOS, instead of silently falling back to `mmap`.
> Test fixes for multiple platforms

- server/go/README.md
- server/go/pkg/server/database.go
- server/go/pkg/server/database_test.go
- server/go/pkg/server/options.go
- server/go/pkg/server/server.go
- server/go/pkg/server/server_test.go
This PR adds an option to the Golang sidecar server to optionally set the `aurora_replica_read_consistency` parameter to allow global write forwarding to function correctly:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-write-forwarding.html
Without this patch, a sidecar connected to a secondary cluster with write forwarding enabled will fail because it cannot write to the database. With this patch, the database session is primed with the value given in the new option and writes function correctly.
> Option to set Aurora replica read consistency

- server/samples/clients/test_clients.sh
- tests/cross-language/scripts/decrypt_all.sh
- tests/cross-language/scripts/encrypt_all.sh
Removed $GOPATH/bin from path as it resolves to /bin which is
not what we want, especially when preceding $GOROOT/bin as it
was
> [cicd] fix go paths

- csharp/SecureMemory/Directory.Build.props
Update C# SecureMemory to 0.2.1 for release.
> Bump C# SecureMemory version

- go/appencryption/pkg/kms/aws.go
Useful to print the error before `continue`. I had to build `asherah-cobhan` binaries with patched Asherah Go to be able to detect the issue documented in https://github.com/godaddy/asherah-cobhan/pull/39.
> Log KMS decrypt errors in Asherah Go

- .github/workflows/ci.yml
- build/csharp/install-dotnet-3.1.sh
- csharp/SecureMemory/SecureMemory/SecureMemory.csproj
- csharp/SecureMemory/scripts/install-dotnet-3.1.sh
This PR provides the minimal changes to fix the security issues Snyk has identified.  It upgrades the relevant packages, and then switches the build of SecureMemory to use sdk 6.0 with 3.1 targeting installed which is required to build the newer packages.  See issue: https://github.com/dotnet/runtime/issues/61602
> Fix snyk issues by updating packages and build sdk

- java/app-encryption/pom.xml
- java/secure-memory/pom.xml
The setup-java [docs](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#extra-setup-for-pomxml) state the this additional config is still required for the maven GPG plugin to avoid errors like `Inappropriate ioctl for device or gpg: signing failed: No such file or directory`
> Add GPG plugin config

- .github/workflows/ci.yml
1. Cache `m2/repository` instead of the complete `m2` directory. This will not overwrite `settings.xml`. Using [this](https://github.com/actions/cache/blob/main/examples.md#java---maven) example.
1. Replace java distribution `adopt` with `temurin`
1. Downgrade server runner to `ubuntu-20.04` because of issues with `apt-get upgrade` on `ubuntu-latest`. See [past issue](https://github.com/actions/runner-images/issues/1605). Created a [new issue ](https://github.com/actions/runner-images/issues/7192) on the actions/runner-images repo.
Change 1 should fix the failing release process. Tested this on a personal repo.
> Fix Java Caches

- CONTRIBUTING.md
- README.md
Contributions and questions should now be handled in GitHub Issues and Discussions.
> Remove legacy Slack references

- .github/workflows/ci.yml
- csharp/Logging/Directory.Build.props
- csharp/Logging/Logging.Tests/Logging.Tests.csproj
- csharp/Logging/Logging/Logging.csproj
- Migrate Logging projects to .NET 6.0 (from .NET Core 3.1)
> [csharp logging] migrate to .NET 6.0

- .github/workflows/ci.yml
- csharp/SecureMemory/Directory.Build.props
- csharp/SecureMemory/SecureMemory.Tests/SecureMemory.Tests.csproj
- Migrate SecureMemory projects to .NET 6.0 (from .NET Core 3.1)
> [csharp securememory] migrate to .NET 6.0

- .github/workflows/ci.yml
- csharp/AppEncryption/AppEncryption.IntegrationTests/AppEncryption.IntegrationTests.csproj
- csharp/AppEncryption/AppEncryption.Tests/AppEncryption.Tests.csproj
- csharp/AppEncryption/AppEncryption/AppEncryption.csproj
- csharp/AppEncryption/Crypto/Crypto.csproj
- csharp/AppEncryption/Directory.Build.props
- Migrate AppEncryption projects to .NET 6.0 (from .NET Core 3.1)
- Update dependencies
> [csharp appencryption] migrate to .NET 6.0

- .github/workflows/ci.yml
- samples/csharp/ReferenceApp/ReferenceApp/ReferenceApp.csproj
- Migrate ReferenceApp projects to .NET 6.0 (from .NET Core 3.1)
- Upgrade AppEncryption to v0.2.10
> [csharp referenceapp] migrate to .NET 6.0, update deps

- .github/workflows/cross-language-validation.yml
Updated Cross-Language Tests job to include a "Download Go dependencies" step prior to linting.
> Add "Download Go dependencies" step to Cross-Language Tests job

- samples/java/reference-app/pom.xml
- server/java/pom.xml
- tests/cross-language/java/pom.xml
Upgraded mysql-connector-java to 8.4.0 and updated POM dependency to use [new Maven coordinates](https://blogs.oracle.com/mysql/post/mysql-connectorj-has-new-maven-coordinates)
> [Java] Upgrade mysql-connector-java to 8.4.0

- csharp/AppEncryption/AppEncryption/AppEncryption.csproj
- csharp/AppEncryption/Crypto/Crypto.csproj
- csharp/AppEncryption/Directory.Build.props
- upgraded dependencies:
- GoDaddy.Asherah.Logging -> 0.1.6
- GoDaddy.Asherah.SecureMemory -> 0.2.5
- System.Text.Json -> 9.0.1
- bump version to 0.2.11
> [csharp appencryption] upgrades deps, bump version

- .github/workflows/java-appencryption-ci.yml
- Updated push trigger for "[Java] AppEncryption CI" to ignore release branches.
> [java ci] ignore release branches on push

- .github/workflows/cross-language-validation.yml
- tests/cross-language/go/decrypt_test.go
- tests/cross-language/go/encrypt_test.go
- tests/cross-language/scripts/decrypt_all.sh
- tests/cross-language/scripts/encrypt_all.sh
- added test functions for encrypt/decrypt feature tests
- updated testing scripts, replacing use of `godog` with `go test`
- removed godog installation from "Build the Go project" step
> [go cltf] stop using deprecated godog CLI

- tests/cross-language/go/decrypt_test.go
- tests/cross-language/go/encrypt_test.go
- tests/cross-language/scripts/decrypt_all.sh
- tests/cross-language/scripts/encrypt_all.sh
- Adds support for godog commandline flags
**NOTE**: This is required to support custom feature paths for downstream projects
> [go cltf] add support for godog commandline flags

- build/csharp/release_prod.sh
- build/go/release_prod.sh
- build/java/release_prod.sh
- Removed the "DRY RUN" logging/early exit
- Tags will now be created using the second parent of the merge commit, i.e., the commit from the main branch
- Tags will no longer be created using the `--force` option. If a tag already exists then something has gone wrong and the operation should fail accordingly.
> [cicd] updated release scripts

- java/app-encryption/README.md
- removed reference and links to the long-deleted java test app
> [java appencryption] removed dead links from readme

- csharp/SecureMemory/Directory.Build.props
- csharp/SecureMemory/SecureMemory.Tests/ProtectedMemoryImpl/Libc/LibcProtectedMemoryAllocatorTest.cs
- csharp/SecureMemory/SecureMemory.Tests/SecureMemorySecretTest.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/Libc/LibcProtectedMemoryAllocatorLP64.cs
- csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/Linux/LinuxOpenSSL11ProtectedMemoryAllocatorLP64.cs
- csharp/SecureMemory/SecureMemory/SecureMemoryAllocationFailedException.cs
- csharp/SecureMemory/SecureMemory/SecureMemoryException.cs
This change adds inner exception constructor to SecureMemoryException and SecureMemoryAllocationFailedException classes to enable proper exception chaining. The LibcProtectedMemoryAllocatorLP64 and LinuxOpenSSL11ProtectedMemoryAllocatorLP64 implementations were updated to wrap exceptions from SetNoDump in SecureMemoryAllocationFailedException with appropriate error context. Tests were also updated to verify the new exception wrapping behavior.
> [csharp securememory] exception handling updates (fix tests)

- .github/workflows/cross-language-validation.yml
- .github/workflows/csharp-appencryption-ci.yml
- .github/workflows/csharp-appencryption-integration.yml
- .github/workflows/csharp-appencryption-release.yml
- .github/workflows/csharp-logging-ci.yml
- .github/workflows/csharp-logging-release.yml
- .github/workflows/csharp-pr.yml
- .github/workflows/csharp-securememory-ci.yml
- .github/workflows/csharp-securememory-release.yml
- csharp/AppEncryption/AppEncryption.IntegrationTests/AppEncryption.IntegrationTests.csproj
- csharp/AppEncryption/AppEncryption.Tests/AppEncryption.Tests.csproj
- csharp/AppEncryption/AppEncryption.Tests/AppEncryption/Persistence/MySqlContainerFixture.cs
- csharp/AppEncryption/AppEncryption/AppEncryption.csproj
- csharp/AppEncryption/Crypto/Crypto.csproj
- csharp/Logging/Logging.Tests/Logging.Tests.csproj
- csharp/Logging/Logging/Logging.csproj
- csharp/SecureMemory/PlatformNative/PlatformNative.csproj
- csharp/SecureMemory/SecureMemory.Tests/SecureMemory.Tests.csproj
- csharp/SecureMemory/SecureMemory/SecureMemory.csproj
- samples/csharp/ReferenceApp/ReferenceApp/ReferenceApp.csproj
- tests/cross-language/csharp/Cltf.csproj
Resolves #1183
- Added multi-target framework support for all C# projects to target net8.0 and net9.0
- Dropped support for netstandard2.1
- Test projects updated to target net9.0
- Updated CI/CD workflows:
- Updated cache keys for C# projects to be more specific and granular
- Use .NET 9.0 SDK container images
- [AppEncryption CI] Added MySQL 8.0 support and fixed connection string configuration
- [SecureMemory CI] Added libssl installation step to fix …
> [csharp] multi-target framework updates for .net 8.0 and 9.0

- csharp/AppEncryption/AppEncryption.IntegrationTests/AppEncryption.IntegrationTests.csproj
- csharp/AppEncryption/AppEncryption.Tests/AppEncryption.Tests.csproj
- csharp/AppEncryption/AppEncryption.Tests/AppEncryption/Kms/AwsKeyManagementServiceImplTest.cs
- csharp/AppEncryption/AppEncryption.Tests/AppEncryption/Persistence/DynamoDBContainerFixture.cs
- csharp/AppEncryption/AppEncryption.Tests/AppEncryption/Persistence/DynamoDbMetastoreImplTest.cs
- csharp/AppEncryption/AppEncryption/AppEncryption.csproj
- csharp/AppEncryption/AppEncryption/Kms/AwsKeyManagementServiceImpl.cs
- csharp/AppEncryption/AppEncryption/Kms/AwsKmsClientFactory.cs
- csharp/AppEncryption/AppEncryption/Persistence/DynamoDbMetastoreImpl.cs
- csharp/AppEncryption/Directory.Build.props
- csharp/AppEncryption/scripts/test.sh
- Replace synchronous AWS client methods with async/await pattern
- Update KMS operations to use request/response objects instead of parameter overloads
- Migrate DynamoDB Table.LoadTable to TableBuilder pattern
- Fix test mocks to match new SDK response types and async methods
- Update DynamoDB container image to v2.6.0 for test compatibility
- Maintain backward compatibility for credential handling and error management
All tests passing with full KMS …
> [csharp appencryption] Migrate to AWS SDK v4

- .github/workflows/cross-language-validation.yml
- .github/workflows/go-appencryption-bench.yml
- .github/workflows/go-appencryption-ci.yml
- .github/workflows/go-appencryption-integration.yml
- .github/workflows/go-pr.yml
- .github/workflows/go-securememory-bench.yml
- .github/workflows/go-securememory-ci.yml
- .github/workflows/java-appencryption-ci.yml
- .github/workflows/java-appencryption-integration.yml
- .github/workflows/java-appencryption-release.yml
- .github/workflows/java-pr.yml
- .github/workflows/java-securememory-ci.yml
- .github/workflows/java-securememory-release.yml
- bump actions/setup-java from 4.2.1 to 4.7.1
- bump actions/setup-go from 5.2.0 to 5.5.0
- bump actions/setup-python from 5.1.1 to 5.6.0
> [ci] bump actions/setup-go to v5.5.0 and actions/setup-java to v4.7.1

- csharp/AppEncryption/Crypto/Crypto.csproj
- csharp/AppEncryption/Directory.Build.props
- Upgrade GoDaddy.Asherah.Logging to v0.3.0
- Upgrade GoDaddy.Asherah.SecureMemory to v0.4.0
- Bump version to 0.6.0
> [csharp appencryption] upgrade deps, bump version

- go/appencryption/internal/bytes.go
- Replace manual byte zeroing loop with Go's built-in `clear()` function
- Fixes critical security vulnerability where sensitive key material remains in memory
- The `clear()` builtin is guaranteed not to be optimized away by the compiler
**Current code in `internal/bytes.go`:**
```go
func MemClr(buf []byte) {
for i := range buf {
buf[i] = 0  // ❌ Compiler can DELETE this entire loop\!
}
runtime.KeepAlive(buf)  // ⚠️ Only prevents GC, NOT optimization\!
}
```
**Why this is a CRITICAL vulnerability:**
1. **Dead Store Elimination**: Modern Go compilers optimize away "useless" operations. Since no code reads from `buf` after zeroing, the compiler sees this as a "dead store" and can completely remove the zeroing loop.
2. **runtime.KeepAlive() Doesn't Help**: This only tells the garbage …
> fix: use Go's built-in clear() for secure memory wiping

- csharp/AppEncryption/AppEncryption.Tests/AppEncryption/Persistence/DynamoDbMetastoreImplTest.cs
- csharp/AppEncryption/AppEncryption/Persistence/DynamoDbMetastoreImpl.cs
- csharp/AppEncryption/README.md
fixes #1502 
- Fixes an issue with an unneeded and possibly dangerous dispose method in the DynamoDbMetastoreImpl builder that was recently introduced.
- Adds ability to "bring your own IAmazonDynamoDB client" into the Builder that is more friendly with applications using a singleton client in their application and/or dependency injection facades
> Fixed disposable issue and added ability to bring your own client
